### ISSUE TITLE
last update not loaded

### ISSUE THREAD

**Issue by comonier** [ElmHoe/AntiBow#13]
[00:02:50] [Server thread/ERROR]: Error occurred while enabling AntiBow v1.2.9 (Is it up to date?)
java.lang.NoClassDefFoundError: uk/co/ElmHoe/Bukkit/Utilities/HTTPUtility
	at uk.co.ElmHoe.Bukkit.AntiBow.updateChecking(AntiBow.java:458) ~[?:?]
	at uk.co.ElmHoe.Bukkit.AntiBow.onEnable(AntiBow.java:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: uk.co.ElmHoe.Bukkit.Utilities.HTTPUtility
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-d21162c-61e0c69]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	... 13 more

**Comment by comonier** [comment]
well 4 days with no response, i will back to last build

**Comment by ElmHoe** [comment]
@comonier My apologies, I somehow missed this issue.

I fixed this in the lastest spigot build within around 4 hours, it's due to a required class not being exported with it. I apologies about this but the latest spigot build doesn't have this issue.
